### PR TITLE
Alternative zoom

### PR DESCRIPTION
**Pull request by MelonHell**
My alternate scoping code from issue #103.
I wrote this for myself, so the code is bad enough, but I hope it helps to add this

new scope config
```yml
Scope:
  Trigger: <trigger serializer>
  Night_Vision: <true/false>
  Zoom_Levels: <double list of zoom levels from 1 to 10>
  Mechanics: <MechanicsSerializer>
  Stacking_Mechanics: <MechanicsSerializer>
  Shoot_Delay_After_Scope: <ticks>
  Zoom_Off:
    Trigger: <trigger serializer>
    Mechanics: <MechanicsSerializer>
```
example
```yml
Scope:
  Zoom_Levels:
    - 2.0 # means 2x scope
    - 4.0 # means 4x scope
    - 8.0 # means 8x scope
  Stacking_Mechanics:
    Sounds:
      - "custom:scope.in-0.5-1-0-0.1"
```

### CODE REVIEW

**Comment by MelonHell** [comment]
Still need to remake CrackShotConverter for the new system

**Review by CJCrafter — COMMENTED** [review]
Just took some time to look at it.. The serializer stuff looks good, you were very thorough. I am sorry I didn't look at this sooner. I have 0 clue how the packet stuff works for the FOV changes, so I will let DeeCaaD take a look at that. 

I also love the changes to the Scope config, makes it much simpler. However, I would like to see a shorthand like ` Zoom_Levels: 1.5` instead of
```yaml
 Zoom_Levels:
- 1.5
```
whenever you want only 1 value.

**Comment by MelonHell** [comment]
> Just took some time to look at it.. The serializer stuff looks good, you were very thorough. I am sorry I didn't look at this sooner. I have 0 clue how the packet stuff works for the FOV changes, so I will let DeeCaaD take a look at that. 
> 
> I also love the changes to the Scope config, makes it much simpler. However, I would like to see a shorthand like ` Zoom_Levels: 1.5` instead of
> ```yaml
>  Zoom_Levels:
> - 1.5
> ```
> whenever you want only 1 value. 

I made zoom_levels as a list to make it easy to set up sniper rifles with multiple zoom levels.  I find this to be better than zoom stacking as it allows you to fine-tune the desired result.

**Review by DeeCaaD — APPROVED** [review]
Everything is good to go now

**Pull request merged**
